plugins:
    - jekyll-feed

title: Max Crone
description: Max Crone is a computer security and cloud engineer currently in his Master's at Aalto University in Finland.

permalink: /:categories/:title

collections:
  food:
    output: true
    permalink: /:collection/:title
