plugins:
    - jekyll-feed

title: Max Crone
description: Max Crone is a computer engineer exploring life in The Netherlands.
url: https://maxcrone.org

permalink: /:categories/:title

collections:
  food:
    output: true
    permalink: /:collection/:title
  books:
    output: true
    permalink: /:collection/:title
  flash:
    output: true
    permalink: /:collection/:year/:month/:day
  albums:
    output: true
    permalink: /a/:title
    order:
      - portraits.md
      - street.md
      - events.md
      - nature.md
      - food.md
  photos:
    output: true
    permalink: /photo/:title
    sort_by: date
