plugins:
    - jekyll-feed

title: Max Crone
description: Max Crone is a computer engineer exploring life in The Netherlands.

permalink: /:categories/:title

collections:
  food:
    output: true
    permalink: /:collection/:title
  books:
    output: true
    permalink: /:collection/:title
