[[places]]
name = "The city garden"
date = 2025-03-27
desc = """
I was attending Real World Crypto in the city (amazing conference with many smart people).
And this park happened to become our anchor point around which several activities revolved.
Just after arriving I sat down here for a while on my quick photo walk.
At the end of the first day we gathered in this park with a small group of cryptographers to discuss
ways in which we are able to help our communities in these times.
And later in the week we walked through here a few more times.
After the conference ended, I came here again to decompress a bit.
Locals flocked to the many benches to catch up with friends or colleagues.
Or to just relax in the comfortably warm spring air.
"""
lat = 42.694694
lon = 23.325521
sound = "/assets/audio/2025-03-27-sofia-city-garden.mp3"

[[places]]
name = "Ya Kun Kaya Toast"
date = 2025-02-18
desc = """
I had to start my twenty-four hour layover in Singapore with kaya toast.
So I walked to a branch of Ya Kun, already drenched in sweat by the time I got there.
The black coffee, soft boiled eggs, and toast with sweet butter.
Sweltering morning heat and the clatter of plates and retirees catching up with friends.
It promised to be an adventurous day.
"""
lat = 1.3003193
lon = 103.8520479
sound = "/assets/audio/2025-02-18-ya-kun-kaya-toast.m4a"

[[places]]
name = "Amoy street food center"
date = 2025-02-18
desc = """
Street food stalls in Singapore have been centralized into big hawker centers.
The much more famous one that appears in most annals of tourism is the Maxwell food centre not too far from here.
I went there first, but it was a weird mix of half tourists and half locals (as far as I am able to tell).
So I continued walking and ran into this one.
Two stories high, full of hawker stalls.
And there it was almost exclusively local office workers on their lunch breaks with colleagues.
Definitely something else than the sad state of office lunch options in the Netherlands.
(Payment options are either cash or one of the 20+ QR codes for different payment apps that I saw plastered onto some stalls.)
"""
lat = 1.279400
lon = 103.846790
sound = "/assets/audio/2025-02-18-amoy-street-food-center.m4a"

[[places]]
name = "Milford Sound"
date = 2025-02-12
desc = """
The obligatory cruise through Milford Sound.
This place is purely tourism, but the natural landscape is still stunning.
The drive there was also beautiful, in its early morning light.
It apparently hadn't rained for more than six weeks, which is highly unusual for Milford Sound.
But it meant that our boat ride was luxuriously sunny.
"""
lat = -44.63877
lon = 167.88161
sound = "/assets/audio/2025-02-12-milford-sound.m4a"

[[places]]
name = "Waipohatu waterfall track"
date = 2025-02-11
desc = """
This is a track through some of the rare old-growth bush (this side of New Zealand is mostly one big pasture now).
I'd camped at the start of the trail, and when I woke up in the morning I was the only one there.
Quick wash in a stream, some sandwiches with peanut butter, camera in the bag and go.
The two waterfalls are roughly halfway along the trail.
Both immensely beautiful and powerful, in the middle of the dense bush.
Have never felt more like an explorer than I felt that morning.
"""
lat = -46.602938
lon = 169.019543
sound = "/assets/audio/2025-02-11-waipohatu.m4a"

[[places]]
name = "Aramoana beach"
date = 2025-02-09
desc = """
To get to this remote beach I had to drive along a winding road hugging the mountains on one side
and the water from the bay glistering on the other side (the sun was already setting).
It appeared to mostly be a surfers beach.
The only non-surfer there, was a man with his family, who was carrying fishing cages into the ocean
and reeling them back in a few minutes later, all the while being soaked through.
I walked all the way along the beach until large boulders prevented me from continuing.
There I heard small streams of water rushing down the mountainside, almost as if the stone was weeping.
I spent the remainder of the evening listening to the sea lions and feeling the ocean breeze on my face.
I camped in my van right besides the beach.
"""
lat = -45.766402
lon = 170.696374
sound = "/assets/audio/2025-02-09-aramoana-beach.m4a"

[[places]]
name = "Stephan McLaughlan"
date = 2025-02-03
desc = """
I got lost in the huge but hidden Nicholas building in the middle of Melbourne (look it up on Atlas Obscura).
Every floor was a square circle with old doors behind which should be a multitude of different small businesses and workshops and parlors and clubs.
But I had come at the wrong time of the week.
All the way at the top, I found one door was open.
It led a small art exhibition with a handful of paintings from three different artists.
Stephan McLaughlin has been running that exhibition space for longer than I'm alive.
And he has stories to tell.
So I just listened while he told, and we gazed through the windows overlooking the city.
"""
lat = -37.816877
lon = 144.966849
sound = "/assets/audio/2025-02-03-stephen-mclaughlan.m4a"

[[places]]
name = "La Jolla Cove"
date = 2024-10-20
desc = """
Sitting right besides the great Pacific ocean.
This was a very touristy spot, not only for humans.
Plenty of sea lions and seals chilling on the rocks.
Flocks of seagulls swerving in and out.
I spent the rest of the day reading on the beach, while the sun slowly set and the tide pools filled up
with the water left behind by the retreating ocean.
Richard Powers's *Playground* took two characters on a trip to the Scripps institution of oceanography,
only a few kilometers from where I had my bare feet in the sand, and then even to La Jolla itself.
I loved smelling the same air, wading through the same water, and seeing similar small ocean life.
It felt like I was part of the book.
"""
lat = 32.850972
lon = -117.273467
sound = "/assets/audio/2024-10-20-la-jolla-cove.m4a"

[[places]]
name = "Cucina 35"
date = 2024-10-20
desc = """
I was in San Diego the week before for a conference and decided to stay another weekend to explore more of the city.
On the Sunday, I walked over from my hotel in downtown to this traditional Mexican breakfast restaurant.
They serve chilaquiles; basically tortillas simmered in salsa.
I had them with mushrooms, refried beans, and a small tamale on the side.
The restaurant was filled with joyful families and from time to time the staff all came out
making as much noise as they could, rattling and whooping, to celebrate a table.
"""
lat = 32.720431
lon = -117.159175
sound = "/assets/audio/2024-10-20-cocina-35.m4a"

[[places]]
name = "Sunday morning after a festival on Vlieland"
date = 2024-09-01
desc = """
I went to volunteer at the Into the Great Wide Open festival on Vlieland.
Worked in the crew kitchen, where we helped to produce breakfast, lunch, and dinner for the thousand people who helped make the festival a reality.
Music is played at different stages in forests and among the dunes.
Locations are beautiful, the people are beautiful, and the island is incredibly peaceful.
The Sunday morning is the end of the festival, when everyone is still reeling from all their experiences but also very, very tired.
We're sitting at a small square on the camping, while people are ordering coffee, talking amongst themselves, or quietly listening to some soft music."""
lat = 53.304196
lon = 5.079561
sound = "/assets/audio/2024-09-01-stortemelk-itgwo.m4a"

[[places]]
name = "Biking through the rain in Westerpark"
date = 2024-07-09
desc = """
Rushing back to the ferry after a good bouldering session,
I got caught in the rain while going through Westerpark.
It was a mild summer evening, with people out all across the park for late evening picnics up until the rain came.
I slowed down and listened to the birds that were joyous for the refreshing tide."""
lat = 52.38827
lon = 4.87183
sound = "/assets/audio/2024-07-09-westerpark.m4a"

[[places]]
name = "Harp on the streets in Trier"
date = 2024-08-18
desc = """
After a week with friends in the Alsace, France, we were driving back to The Netherlands through Germany
and stopped in Trier for a lunch break and some quick sightseeing.
After visiting the old Roman amphitheater we strolled down into the city center and ran into
a man playing beautifully quiet harp songs in the palace's gardens while whistling along to his own tunes."""
lat = 49.752062
lon = 6.642658
sound = "/assets/audio/2024-08-18-trier.m4a"

[[places]]
name = "Soundcheck in Soultzmatt"
date = 2024-08-15
desc = """
On a trip with friends, we were driving back from a day of adventures and stumbled on this small village.
We saw people in traditional clothing getting out of their cars and carrying instruments down to a small fair.
So naturally we stopped as well, and sat amongst the locals who were celebrating summer with food, wine, and music."""
lat = 47.969127
lon = 7.222702
sound = "/assets/audio/2024-08-15-soultzmatt.m4a"

[[places]]
name = "Waterleidingduinen"
date = 2024-06-23
desc = """
Went on a long walk through the dunes near Amsterdam where the municipality extracts drinking water.
We brought sandwiches that we ate on top of a hill, sun blasting, wind lazily throwing us some warm sand.
Talking about pastoral fantasies and nostalgic summer vacations.
After we'd topped the dunes near the sea, we snoozed on the beach, skinny dipped in the sea, and ate melon while its juice dripped down our faces."""
lat = 52.34442
lon = 4.53606
sound = "/assets/audio/2024-06-23-waterleidingduinen.m4a"

[[places]]
name = "Kappabashi kitchen tools street"
date = 2024-05-31
desc = """
Browsing through Utsuwazoshi, a store with only wooden kitchen tools, along this inspiring street.
In one of the shops before it, I bought a beautiful nakiri knife made from carbon.
In another, I was eyeing some incredible copper pans until I told myself that it would be a bit of a hassle to bring them back with me."""
lat = 35.7146838
lon = 139.7881882
sound = "/assets/audio/2024-05-31-utsuwazoshi.m4a"

[[places]]
name = "Shibuya station"
date = 2024-05-30
desc = """
The fourth busiest railway station in the world.
Just outside lie some of these crazy squares where all pedestrians cross (in multiple diagonal degrees) at the same time.
I just walked around this part of the city for a while, taking photos of streets and people, while an approaching thunderstorm loomed."""
lat = 35.6580339
lon = 139.6990609
sound = "/assets/audio/2024-05-30-shibuya.m4a"

[[places]]
name = "Kinkaku-ji"
date = 2024-05-29
desc = """
The Deer Garden Temple is apparently one of Kyoto's most popular attractions.
People were throwing coins at small statues dotted along the path.
And later on, a group of Japanese school children became giggly obsessed with me."""
lat = 35.03952
lon = 135.72958
sound = "/assets/audio/2024-05-29-kinkaku-ji.m4a"

[[places]]
name = "Local sushi restaurant"
date = 2024-05-28
desc = """
After bouldering at the nearby Galera climbing gym I had found my way to this local sushi conveyor belt restaurant,
where everyone seemed to know each other.
I nestled right across from the chef, between two groups of patrons.
No one spoke any English, but everyone kindly tried to help me to order as much good food as possible."""
lat = 34.6605404
lon = 135.4750963
sound = "/assets/audio/2024-05-28-sushi.m4a"

[[places]]
name = "Subtropical rainstorm in Umeda"
date = 2024-05-28
desc = """
We had just come out of Camera Obayashi, mostly just intimidated by all the beautiful camera's and their astronomical valuations in yen, when we got caught in a heavy downpour.
While waiting for the pedestrian light, our shoes had already been soaked."""
lat = 34.6993987
lon = 135.4956517
sound = "/assets/audio/2024-05-28-osaka-subtropical-rain.m4a"

[[places]]
name = "Nankai line"
date = 2024-05-28
desc = """
I stayed in a lovely old lady's bed and breakfast for a few days and to get into the city I would take the Nankai railway line.
Warm raindrops were peckering on the train while we approached Imamiyaebisu station."""
lat = 34.654984
lon = 135.4989852
sound = "/assets/audio/2024-05-28-nankai.m4a"

[[places]]
name = "Osaka Castle plum gardens"
date = 2024-05-20
desc = """
It was past their flowering, but the plum trees still smelt sweet and dreamy.
Went there on one of my first days and came back again the next week with a friend."""
lat = 34.6867273
lon = 135.5278187
sound = "/assets/audio/2024-05-20-osaka-castle-plum-garden.m4a"

[[places]]
name = "Loonse en Drunense duinen"
date = 2024-05-11
desc = """
I had missed the aurora the previous night, but hoped to catch a glimpse of it now, despite rapidly dwindling prospects.
Multiple other people were similarly hopeful and had already settled on the warm sand as the darkness slowly got darker.
Got some nice photos, but no aurora.
Instead, we listened to this frog opera, which was also beautiful, in its own way."""
lat = 51.63992
lon = 5.10824
sound = "/assets/audio/2024-05-11-loonse-drunense-duinen.m4a"

[[places]]
name = "Niagara Falls"
date = 2024-04-20
desc = """
Visited this touristy place on my last day in Canada."""
lat = 43.07919
lon = -79.07816
sound = "/assets/audio/2024-04-20-niagara-falls.m4a"

[[places]]
name = "Thousand Islands national park, Canada"
date = 2024-04-18
desc = """
Didn't have a boat and the season wasn't opened yet, so I had to be content with hikes on the mainland."""
lat = 44.45315
lon = -75.86468
sound = "/assets/audio/2024-04-18-thousand-islands.m4a"

[[places]]
name = "Owl's Nest, Prince Edward County, Canada"
date = 2024-04-18
desc = """
Stayed at a homestead of a young family for the night.
They had a also built a beautiful open shed with a swing next to a pond where the frogs were in mating season.
The rest of the night was filled by a full choir of birds."""
lat = 44.04949
lon = -77.52525
sound = "/assets/audio/2024-04-18-owls-nest.m4a"

[[places]]
name = "Forillon national park, Canada"
date = 2024-04-15
desc = """
Tried to go for a hike in-between seasons, but the trail still had a layer of snow that came up to my upper leg.
I struggled for a while, but ended up just listening to the water."""
lat = 48.86151
lon = -64.38167
sound = "/assets/audio/2024-04-15-forillon.m4a"

[[places]]
name = "Badhus, Amsterdam"
date = 2023-11-10
desc = """
The floating sauna where I volunteer as a host."""
lat = 52.39322
lon = 4.90984
sound = "/assets/audio/2023-11-10-badhus.aac"

[[places]]
name = "Train from Lugano to Basel, Switzerland"
date = 2023-09-22
desc = """
Our train ride through Switzerland brought us past beautiful mountain ranges where
all the meltwater rushed down waterfalls for kilometers on end.
Meanwhile, the rain trickled over our railwagon."""
lat = 46.7339
lon = 8.7284
sound = "/assets/audio/2023-09-22-train-to-basel.aac"

[[places]]
name = "Cademario, Lugano, Switzerland"
date = 2023-09-21
desc = """
While we stayed in the Kurhaus, we tried to hike the hill in the window of opportunity between all the rain.
Or so we thought.
The rain started to fall around us again, but at least we were relatively well protected whilst among the trees."""
lat = 46.02287
lon = 8.89013
sound = "/assets/audio/2023-09-21-cademario.aac"

[[places]]
name = "Castello Brown, Portofino, Italy"
date = 2023-09-17
desc = """
We'd climbed the hill on top of which the castello stood, overlooking Portofino.
Now we longed to cool off in the seductive waves of the sea below."""
lat = 44.30242
lon = 9.21404
sound = "/assets/audio/2023-09-17-portofino-castle.aac"

[[places]]
name = "Bright Computing's datacenter, Sloterdijk"
date = 2022-10-27
desc = """
My first job out of college had an office in Amsterdam, where they colocated a few racks in the tower's basement.
I had to fiddle around in it from time to time when I needed to write integrations with new hardware."""
lat =  52.3856719
lon = 4.8432119
sound = "/assets/audio/2022-10-27-bright-computing-datacenter.aac"
